### PR TITLE
Practice 1, PR 1

### PR DESCRIPTION
**Pull request by nick-krasnitskiy**
1. iOS Project was created.
2. UI was created.
2. Task was resolved.
3. Splash screen was added.
4. App icons were added.

### CODE REVIEW

**Comment by vasilevkin** [comment]
Write commit comments and pr description using present simple tense.
(Not required to change anything done already)

**Review by vasilevkin — APPROVED** [review]
Great start!
Proceed with additional tasks.

**Comment by nick-krasnitskiy** [comment]
> Write commit comments and pr description using present simple tense.
> (Not required to change anything done already)

Ok. Thanks a lot for your remark.

**Comment by nick-krasnitskiy** [comment]
> Great start!
> Proceed with additional tasks.

Ok. Thank you!

**Pull request merged**
